### PR TITLE
I think this should work now

### PR DESCRIPTION
**Pull request by Sydney-Thomas**

### CODE REVIEW

**Comment by mwang87** [comment]
The images need to be relative to the docs folder not an absolute path. CHeckout the GNPS docs as an example.

**Comment by Sydney-Thomas** [comment]
Okay, looks like my most recent commits should fix that.

**Comment by Sydney-Thomas** [comment]
#5 resolve

**Comment by mwang87** [comment]
Oh there is a conflict against the visualizer, can you resolve the conflicts?

**Comment by Sydney-Thomas** [comment]
#5 resolved

**Pull request merged**
